In [29]:
import plotly.express as px
import pandas as pd

In [30]:
data_set = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/loan_approval_data.csv')

In [31]:
Transposed = data_set.describe().transpose()
Transposed

,count,mean,std,min,25%,50%,75%,max
id,58645.0,29322.000000,16929.497605,0.00,14661.00,29322.00,43983.00,58644.00
age,58639.0,27.550913,6.033217,20.00,23.00,26.00,30.00,123.00
income,58645.0,64046.172871,37931.106978,4200.00,42000.00,58000.00,75600.00,1900000.00
emplyment_length,58645.0,4.703487,4.004982,0.00,2.00,4.00,7.00,150.00
loan_amount,58645.0,9217.556518,5563.807384,500.00,5000.00,8000.00,12000.00,35000.00
loan_interest_rate,58634.0,10.677526,3.036034,-11.14,7.88,10.75,12.99,23.22
loan_income_ratio,58645.0,0.159238,0.091692,0.00,0.09,0.14,0.21,0.83
credit_history_length,58645.0,5.813556,4.029196,2.00,3.00,4.00,8.00,30.00
loan_approval_status,58645.0,0.142382,0.349445,0.00,0.00,0.00,0.00,1.00
max_allowed_loan,58645.0,69754.717828,61750.913820,-2426900.00,38003.00,62392.00,92716.00,2638778.00

In [32]:
Age_fig = px.histogram(data_frame=data_set, x='age')
Age_fig.show()

In [18]:
Loan_Approval_with_Employment = px.histogram(data_frame = data_set, x='loan_approval_status', color='emplyment_length')
Loan_Approval_with_Employment.show()

In [33]:
data_set.rename({"emplyment_length":"employment_length"}, axis=1, inplace=True)
list(data_set.columns)

['id',
 'age',
 'income',
 'home_ownership',
 'employment_length',
 'loan_intent',
 'loan_amount',
 'loan_interest_rate',
 'loan_income_ratio',
 'payment_default_on_file',
 'credit_history_length',
 'loan_approval_status',
 'max_allowed_loan']

In [34]:
df = data_set.drop(columns=(['id']))
df.describe()

# Example: Replace the 'age' value in the first row (index 0) with None
# First, let's look at the original value
print(f"Original age in row 0: {df.loc[0, 'age']}")

df.loc[0, 'age'] = None

# Now, let's verify the change
print(f"New age in row 0: {df.loc[0, 'age']}")

# To see the updated DataFrame head
# df.head()

Original age in row 0: 21.0
New age in row 0: nan

In [35]:
age_fig = px.box(df, x='age')
age_fig.show()

All ages up from 40 are outliers according to the box plot

In [25]:
income_fig = px.box(df, x='income')
income_fig.show()

All incomes up from 126k are outliers according to the box plot

In [26]:
employmentlength_fig = px.box(df, x='employment_length')
employmentlength_fig.show()

All employment lengths up from 14 years are outliers according to the boxplot

In [36]:
Age_VS_Employmentlength_fig = px.scatter(df, x='age', y='employment_length')
Age_VS_Employmentlength_fig.show()

In [37]:
df[df.employment_length>100]

,age,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_allowed_loan
6008,28.0,60350,MORTGAGE,123,MEDICAL,25000,15.95,0.35,Y,6,1,0
9479,21.0,24000,RENT,150,MEDICAL,1500,14.27,0.06,Y,4,0,23692
56728,21.0,192000,MORTGAGE,123,VENTURE,20000,11.49,0.10,N,2,0,181570

In [40]:
df.loc[6008, 'employment_length'] = None

In [39]:
df.loc[[56728, 9479], 'employment_length'] = None

In [41]:
df[(df.employment_length==41) & (df.age==43)]

,age,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_allowed_loan
44566,43.0,56000,RENT,41.0,HOMEIMPROVEMENT,2000,10.99,0.04,N,14,0,94315

In [43]:
df.employment_length.mean()

np.float64(4.696974864431636)

In [44]:
df.loc[44566, 'employment_length'] = df.employment_length.mean()

In [45]:
df.loc[[56728, 9479, 6008], 'employment_length'] = df.employment_length.mean()

In [46]:
New_Age_VS_Employmentlength_fig = px.scatter(df, x='age', y='employment_length')
New_Age_VS_Employmentlength_fig.show()

In [47]:
df[(df.age==123)]

,age,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_allowed_loan
39792,123.0,36000,MORTGAGE,7.0,PERSONAL,6700,10.75,0.18,N,4,0,81860

In [48]:
df.loc[39792, 'age']=df.age.mean()

The obvious outliers from thebar chart are filered. Now cleaning with consideration about work years and age gap.

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      58638 non-null  float64
 1   income                   58645 non-null  int64
 2   home_ownership           58645 non-null  object
 3   employment_length        58645 non-null  float64
 4   loan_intent              58645 non-null  object
 5   loan_amount              58645 non-null  int64
 6   loan_interest_rate       58634 non-null  float64
 7   loan_income_ratio        58645 non-null  float64
 8   payment_default_on_file  58640 non-null  object
 9   credit_history_length    58645 non-null  int64
 10  loan_approval_status     58645 non-null  int64
 11  max_allowed_loan         58645 non-null  int64
dtypes: float64(4), int64(5), object(3)
memory usage: 5.4+ MB

In [50]:
df[(df.age-18) < (df.employment_length)]

,age,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_allowed_loan
78,40.0,86500,OWN,24.0,EDUCATION,14000,7.29,0.16,N,12,0,14000
212,40.0,149000,MORTGAGE,25.0,HOMEIMPROVEMENT,7000,10.59,0.05,N,14,0,7000
382,21.0,30000,RENT,5.0,HOMEIMPROVEMENT,6500,14.27,0.22,N,4,1,0
383,21.0,31000,RENT,5.0,EDUCATION,10000,11.49,0.32,N,2,1,0
388,21.0,33996,RENT,5.0,MEDICAL,15000,14.96,0.44,NaN,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
58624,24.0,828000,MORTGAGE,8.0,MEDICAL,4800,9.62,0.06,N,2,0,988783
58626,25.0,889000,MORTGAGE,9.0,EDUCATION,4000,11.49,0.05,N,3,0,1107234
58639,35.0,900000,MORTGAGE,18.0,PERSONAL,4500,10.65,0.01,N,6,0,1570477
58640,32.0,1200000,MORTGAGE,16.0,DEBTCONSOLIDATION,16000,6.92,0.13,N,5,0,1903960
58642,22.0,1900000,MORTGAGE,6.0,EDUCATION,1500,15.62,0.00,Y,3,0,2088491

###Splitting the data set df

* one for Loan Approval status Classification modelling

* the other for Regression Modelling of Maximum Loan
Amount for loan-approved clients.

Client features ──▶ Loan Approved? ──▶ Max Allowed Loan

* for the Classification Modelling for loan_approval_status, it is important to hide the max_allowed_loan amount, as it would suggest to the model in training that the loan has been approved.

* for the Regression Model of max_allowed_loan, it is important to filter out only the approved loans.

In [60]:
# Classification data set for loan_approval
Dc = df.drop(columns=['max_allowed_loan', 'loan_interest_rate'])
Dc.head(3)

# The label data should contain only the loan_approval_status
y_cls = Dc['loan_approval_status']

# The feature data must NOT contain the ANSWER (loan_approval_status)
x_cls = Dc.drop(columns=['loan_approval_status'])

In [61]:
y_cls.head()

0    0
1    0
2    0
3    0
4    0
Name: loan_approval_status, dtype: int64

In [62]:
x_cls.head()

,age,income,home_ownership,employment_length,loan_intent,loan_amount,loan_income_ratio,payment_default_on_file,credit_history_length
0,NaN,12000,OWN,0.0,EDUCATION,15000,0.12,N,4
1,21.0,13200,OWN,2.0,EDUCATION,25000,0.19,Y,3
2,23.0,9600,RENT,5.0,MEDICAL,30000,0.31,N,3
3,40.0,182004,RENT,3.0,EDUCATION,35000,0.19,N,11
4,40.0,90000,MORTGAGE,3.0,HOMEIMPROVEMENT,35000,0.39,N,14

In [63]:
# Regression dataset for maximum amount of loan after loan approval.
Dr = df[df['loan_approval_status']!=0]

# check whther any NON APPROVED loan records remain
Dr[(Dr.loan_approval_status==0)]

Empty DataFrame
Columns: [age, income, home_ownership, employment_length, loan_intent, loan_amount, loan_interest_rate, loan_income_ratio, payment_default_on_file, credit_history_length, loan_approval_status, max_allowed_loan]
Index: []

In [64]:
x_rg = Dr.drop(columns='max_allowed_loan')
y_rg = Dr['max_allowed_loan']