In [3]:
import plotly.express as px
import pandas as pd

In [ ]:
data_frame = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Prepared_Mall_Customers.csv')
data_frame.head()

   ID  Sex   Age  Salary  Spending_Score  NewColumn Customer_Satisfaction
0   1    1  19.0    15.0             NaN          1           Unsatisfied
1   2    1   NaN    15.0            81.0          1             Satisfied
2   3    0  20.0    16.0             6.0          1           Unsatisfied
3   4    0  23.0     NaN            77.0          1             Satisfied
4   5    0   NaN     NaN            40.0          1           Unsatisfied

In [ ]:
data_frame.describe()

,ID,Sex,Age,Salary,Spending_Score,NewColumn
count,200.000000,200.000000,197.000000,198.000000,199.000000,200.0
mean,100.500000,0.440000,39.000000,61.005051,50.256281,1.0
std,57.879185,0.497633,14.002915,26.017857,25.876350,0.0
min,1.000000,0.000000,18.000000,15.000000,1.000000,1.0
25%,50.750000,0.000000,29.000000,42.250000,34.500000,1.0
50%,100.500000,0.000000,36.000000,62.000000,50.000000,1.0
75%,150.250000,1.000000,49.000000,78.000000,73.000000,1.0
max,200.000000,1.000000,70.000000,137.000000,99.000000,1.0

1 - Univariate Data Visualisation

In [ ]:


# Construct the histogram plot for the Spending_Score histogram
Spending_Score_fig = px.histogram(data_frame, x='Spending_Score')

# Displaying constructed histogram plot
Spending_Score_fig.show()

In [ ]:
# Construct bar chart plot for Customer_Satisfaction
Customer_Satisfaction_fig = px.bar(data_frame, x = 'Customer_Satisfaction')

#Display constructed bar chart
Customer_Satisfaction_fig.show()

In [ ]:
#Spending_Score_bar = px.bar(x=data_frame['ID'], y=data_frame['Spending_Score'])
Spending_Score_bar = px.bar(data_frame = data_frame, x='ID', y ='Spending_Score', color='Customer_Satisfaction')
Spending_Score_bar.show()

2 - Bivariate Data Visualisations

In [ ]:
Age_VS_Salary_Association_fig = px.scatter(data_frame = data_frame, x='Spending_Score', y = 'Salary', color='Customer_Satisfaction')
Age_VS_Salary_Association_fig.show()

In [ ]:
Spending_Score_Satisfaction_fig = px.histogram(data_frame, x='Age', color='Customer_Satisfaction')
Spending_Score_Satisfaction_fig.show()

In [ ]:
Spending_Score_Satisfaction_fig = px.histogram(data_frame, x='Age', color='Customer_Satisfaction', barmode='overlay')
Spending_Score_Satisfaction_fig.show()

In [ ]:
Spending_Score_Satisfaction_fig = px.bar(data_frame = data_frame, x='Spending_Score', y='ID', color='Salary')
Spending_Score_Satisfaction_fig.show()

Customer_Satisfaction (Satisfied / Not Satisfied) VS Count , colored with Salary

In [ ]:
Customer_Satisfaction_fig = px.bar(data_frame = data_frame, x='Customer_Satisfaction', y='ID', color='Salary')
Customer_Satisfaction_fig.show()

Customer Satisfaction VS Gender(Sex) - Stacked Bar Charts / Bivariate Bar Plots

In [ ]:
data_frame = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Prepared_Mall_Customers.csv')

In [ ]:
data_frame['Sex'] = data_frame['Sex'].map({1:'Female', 0:'Male'})
Customer_Satisfaction_VS_Gender = px.bar(data_frame = data_frame, x = 'Customer_Satisfaction', color='Sex')
Customer_Satisfaction_VS_Gender.show()

Clustered Bar Chart  - Age VS Customer Satisfaction

In [ ]:
Age_Vs_Count_coloredwith_Customer_Satisfaction = px.histogram(data_frame = data_frame, x='Age', color="Customer_Satisfaction" , barmode="group")
Age_Vs_Count_coloredwith_Customer_Satisfaction.show()

Multivariate Plots

In [ ]:
Age_VS_Salary_coloredwith_CustomerSatisfaction = px.scatter(data_frame = data_frame, x = 'Age', y='Salary', color="Customer_Satisfaction")
Age_VS_Salary_coloredwith_CustomerSatisfaction.show()

In [ ]:
Age_VS_Salary_coloredwith_CustomerSatisfaction = px.scatter_3d(data_frame = data_frame, x = 'Age', y='Salary', z='Spending_Score', color="Customer_Satisfaction")
Age_VS_Salary_coloredwith_CustomerSatisfaction.show()

In [ ]:
!git config --global user.email "nimsarakarunaratne@gmail.com"
!git config --global user.name "Nimsara-boop"
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/

In [ ]:
# Change the current working directory to your Colab_Notebooks folder
# The '%' prefix makes this a Colab magic command
%cd /content/drive/MyDrive/Colab_Notebooks

/content/drive/MyDrive/Colab_Notebooks

In [ ]:
# Initialize a new Git repository in this specific folder.
# If you already have a .git folder here, you might want to remove it first
# (e.g., !rm -rf .git) or simply skip this step if it's already initialized correctly.
!git init

Reinitialized existing Git repository in /content/drive/MyDrive/Colab_Notebooks/.git/

In [ ]:
# Configure your Git user details again within this new repository context
!git config user.email "nimsarakarunaratne@gmail.com"
!git config user.name "Nimsara-boop"

In [ ]:
# Add all files in the current directory (Colab_Notebooks) to the staging area
!git add .

In [ ]:
# Commit the staged files
!git commit -m "Initial commit of Colab Notebooks content"

[main 96a851f] Initial commit of Colab Notebooks content
 4 files changed, 204 insertions(+), 1 deletion(-)
 create mode 100644 Copy of DataExploringAndPreparing.ipynb
 create mode 100644 DataExploringAndPreparing.ipynb
 create mode 100644 Prepared_Mall_Customers.csv
 rewrite Redo_Week1.ipynb (83%)

Part (B) Finding Outliers & Extreme Values

In [4]:
#loading data
data_frame = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Prepared_Mall_Customers.csv')

In [5]:
##We used transpose to make the columns rows and the rows columns to twist the table
data_frame.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,200.0,100.500000,57.879185,1.0,50.75,100.5,150.25,200.0
Sex,200.0,0.440000,0.497633,0.0,0.00,0.0,1.00,1.0
Age,197.0,39.000000,14.002915,18.0,29.00,36.0,49.00,70.0
Salary,198.0,61.005051,26.017857,15.0,42.25,62.0,78.00,137.0
Spending_Score,199.0,50.256281,25.876350,1.0,34.50,50.0,73.00,99.0
NewColumn,200.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0

In [13]:
data_frame.head()

   ID  Sex   Age  Salary  Spending_Score  NewColumn Customer_Satisfaction
0   1    1  19.0    15.0             NaN          1           Unsatisfied
1   2    1   NaN    15.0            81.0          1             Satisfied
2   3    0  20.0    16.0             6.0          1           Unsatisfied
3   4    0  23.0     NaN            77.0          1             Satisfied
4   5    0   NaN     NaN            40.0          1           Unsatisfied

In [6]:
df = data_frame.drop(columns=(['ID', 'NewColumn']))
df.describe()

              Sex         Age      Salary  Spending_Score
count  200.000000  197.000000  198.000000      199.000000
mean     0.440000   39.000000   61.005051       50.256281
std      0.497633   14.002915   26.017857       25.876350
min      0.000000   18.000000   15.000000        1.000000
25%      0.000000   29.000000   42.250000       34.500000
50%      0.000000   36.000000   62.000000       50.000000
75%      1.000000   49.000000   78.000000       73.000000
max      1.000000   70.000000  137.000000       99.000000

In [ ]:
Salary_fig = px.histogram(df, x='Salary')
Salary_fig.show()

In [8]:
Age_fig = px.box(df, x='Age')
Age_fig.show()

In [9]:
Salary_fig = px.box(df, x='Salary')
Salary_fig.show()

In [11]:
Age_Salary_fig  = px.scatter(df, x='Age', y='Salary')
Age_Salary_fig.show()

## Using IQR to find outliers

*Outliers fall below (q1 - 1.5IQR) and above (q3+ 1.5IQR)*

In [30]:
def find_outliers_IQR(df):
  q1=df.quantile(0.25)
  q3 = df.quantile(0.75)
  IQR=q3-q1
  outliers = df[((df<(q1-1.5*IQR))|(df>(q3+1.5*IQR)))]
  return outliers

In [32]:
outliers = find_outliers_IQR(df['Salary'])
print("numbers of outliers: "+str(len(outliers)))
outliers

numbers of outliers: 2

198    137.0
199    137.0
Name: Salary, dtype: float64

In [34]:
#dropping outliers
df.drop(df.index[[198, 199]], inplace=True)

In [35]:
#To verify we can check for outliers again
outliers = find_outliers_IQR(df['Salary'])
print("number of outliers: "+str(len(outliers)))
outliers

number of outliers: 0

Series([], Name: Salary, dtype: float64)

In [39]:
df.describe().transpose()

                count       mean        std   min   25%   50%   75%    max
Sex             198.0   0.434343   0.496927   0.0   0.0   0.0   1.0    1.0
Age             195.0  39.082051  14.050844  18.0  28.5  36.0  49.0   70.0
Salary          196.0  60.229592  24.980676  15.0  42.0  61.5  78.0  126.0
Spending_Score  197.0  50.253807  25.799987   1.0  35.0  50.0  73.0   99.0

In [37]:
text = 'this is me'
print(type(text))

<class 'str'>

In [38]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sex                    198 non-null    int64
 1   Age                    195 non-null    float64
 2   Salary                 196 non-null    float64
 3   Spending_Score         197 non-null    float64
 4   Customer_Satisfaction  198 non-null    object
dtypes: float64(3), int64(1), object(1)
memory usage: 7.9+ KB
None

In [15]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/

In [16]:
!git add .

error: open("drive/MyDrive/'22 RBV Batch Reunion  .gform"): Operation not supported
error: unable to index file 'drive/MyDrive/'22 RBV Batch Reunion  .gform'
fatal: adding files failed

In [17]:
%cd MyDive

[Errno 2] No such file or directory: 'MyDive'
/content

In [18]:
%ls

drive/  sample_data/

In [19]:
%cd drive

/content/drive

In [20]:
%cd MyDrive

/content/drive/MyDrive

In [21]:
%cd Colab_Notebooks

/content/drive/MyDrive/Colab_Notebooks

In [22]:
!git init

Reinitialized existing Git repository in /content/drive/MyDrive/Colab_Notebooks/.git/

In [23]:
!git add .

In [24]:
!git commit -m "finding outliers using Box plot and IQR range function calculations."

[main 49b5df1] finding outliers using Box plot and IQR range function calculations.
 3 files changed, 786 insertions(+), 1 deletion(-)
 rewrite DataExploringAndPreparing.ipynb (72%)
 create mode 100644 diabetes.csv
 create mode 100644 slr.csv