In [2]:
import plotly.express as px
import pandas as pd

In [3]:
data_frame = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Prepared_Mall_Customers.csv')
data_frame.head()

   ID  Sex   Age  Salary  Spending_Score  NewColumn Customer_Satisfaction
0   1    1  19.0    15.0             NaN          1           Unsatisfied
1   2    1   NaN    15.0            81.0          1             Satisfied
2   3    0  20.0    16.0             6.0          1           Unsatisfied
3   4    0  23.0     NaN            77.0          1             Satisfied
4   5    0   NaN     NaN            40.0          1           Unsatisfied

In [ ]:
data_frame.describe()

,ID,Sex,Age,Salary,Spending_Score,NewColumn
count,200.000000,200.000000,197.000000,198.000000,199.000000,200.0
mean,100.500000,0.440000,39.000000,61.005051,50.256281,1.0
std,57.879185,0.497633,14.002915,26.017857,25.876350,0.0
min,1.000000,0.000000,18.000000,15.000000,1.000000,1.0
25%,50.750000,0.000000,29.000000,42.250000,34.500000,1.0
50%,100.500000,0.000000,36.000000,62.000000,50.000000,1.0
75%,150.250000,1.000000,49.000000,78.000000,73.000000,1.0
max,200.000000,1.000000,70.000000,137.000000,99.000000,1.0

1 - Univariate Data Visualisation

In [ ]:


# Construct the histogram plot for the Spending_Score histogram
Spending_Score_fig = px.histogram(data_frame, x='Spending_Score')

# Displaying constructed histogram plot
Spending_Score_fig.show()

In [ ]:
# Construct bar chart plot for Customer_Satisfaction
Customer_Satisfaction_fig = px.bar(data_frame, x = 'Customer_Satisfaction')

#Display constructed bar chart
Customer_Satisfaction_fig.show()

In [ ]:
#Spending_Score_bar = px.bar(x=data_frame['ID'], y=data_frame['Spending_Score'])
Spending_Score_bar = px.bar(data_frame = data_frame, x='ID', y ='Spending_Score', color='Customer_Satisfaction')
Spending_Score_bar.show()

2 - Bivariate Data Visualisations

In [ ]:
Age_VS_Salary_Association_fig = px.scatter(data_frame = data_frame, x='Spending_Score', y = 'Salary', color='Customer_Satisfaction')
Age_VS_Salary_Association_fig.show()

In [ ]:
Spending_Score_Satisfaction_fig = px.histogram(data_frame, x='Age', color='Customer_Satisfaction')
Spending_Score_Satisfaction_fig.show()

In [ ]:
Spending_Score_Satisfaction_fig = px.histogram(data_frame, x='Age', color='Customer_Satisfaction', barmode='overlay')
Spending_Score_Satisfaction_fig.show()

In [ ]:
Spending_Score_Satisfaction_fig = px.bar(data_frame = data_frame, x='Spending_Score', y='ID', color='Salary')
Spending_Score_Satisfaction_fig.show()

Customer_Satisfaction (Satisfied / Not Satisfied) VS Count , colored with Salary

In [ ]:
Customer_Satisfaction_fig = px.bar(data_frame = data_frame, x='Customer_Satisfaction', y='ID', color='Salary')
Customer_Satisfaction_fig.show()

Customer Satisfaction VS Gender(Sex) - Stacked Bar Charts / Bivariate Bar Plots

In [4]:
data_frame = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Prepared_Mall_Customers.csv')

In [5]:
data_frame['Sex'] = data_frame['Sex'].map({1:'Female', 0:'Male'})
Customer_Satisfaction_VS_Gender = px.bar(data_frame = data_frame, x = 'Customer_Satisfaction', color='Sex')
Customer_Satisfaction_VS_Gender.show()

Clustered Bar Chart  - Age VS Customer Satisfaction

In [ ]:
Age_Vs_Count_coloredwith_Customer_Satisfaction = px.histogram(data_frame = data_frame, x='Age', color="Customer_Satisfaction" , barmode="group")
Age_Vs_Count_coloredwith_Customer_Satisfaction.show()

Multivariate Plots

In [ ]:
Age_VS_Salary_coloredwith_CustomerSatisfaction = px.scatter(data_frame = data_frame, x = 'Age', y='Salary', color="Customer_Satisfaction")
Age_VS_Salary_coloredwith_CustomerSatisfaction.show()

In [ ]:
Age_VS_Salary_coloredwith_CustomerSatisfaction = px.scatter_3d(data_frame = data_frame, x = 'Age', y='Salary', z='Spending_Score', color="Customer_Satisfaction")
Age_VS_Salary_coloredwith_CustomerSatisfaction.show()

In [ ]:
!git config --global user.email "nimsarakarunaratne@gmail.com"
!git config --global user.name "Nimsara-boop"
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/

In [ ]:
# Change the current working directory to your Colab_Notebooks folder
# The '%' prefix makes this a Colab magic command
%cd /content/drive/MyDrive/Colab_Notebooks

/content/drive/MyDrive/Colab_Notebooks

In [ ]:
# Initialize a new Git repository in this specific folder.
# If you already have a .git folder here, you might want to remove it first
# (e.g., !rm -rf .git) or simply skip this step if it's already initialized correctly.
!git init

Reinitialized existing Git repository in /content/drive/MyDrive/Colab_Notebooks/.git/

In [ ]:
# Configure your Git user details again within this new repository context
!git config user.email "nimsarakarunaratne@gmail.com"
!git config user.name "Nimsara-boop"

In [ ]:
# Add all files in the current directory (Colab_Notebooks) to the staging area
!git add .

In [ ]:
# Commit the staged files
!git commit -m "Initial commit of Colab Notebooks content"

[main 96a851f] Initial commit of Colab Notebooks content
 4 files changed, 204 insertions(+), 1 deletion(-)
 create mode 100644 Copy of DataExploringAndPreparing.ipynb
 create mode 100644 DataExploringAndPreparing.ipynb
 create mode 100644 Prepared_Mall_Customers.csv
 rewrite Redo_Week1.ipynb (83%)

Part (B) Finding Outliers & Extreme Values

In [6]:
#loading data
data_frame = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Prepared_Mall_Customers.csv')

In [ ]:
##We used transpose to make the columns rows and the rows columns to twist the table
data_frame.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,200.0,100.500000,57.879185,1.0,50.75,100.5,150.25,200.0
Sex,200.0,0.440000,0.497633,0.0,0.00,0.0,1.00,1.0
Age,197.0,39.000000,14.002915,18.0,29.00,36.0,49.00,70.0
Salary,198.0,61.005051,26.017857,15.0,42.25,62.0,78.00,137.0
Spending_Score,199.0,50.256281,25.876350,1.0,34.50,50.0,73.00,99.0
NewColumn,200.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0

In [ ]:
data_frame.head()

   ID  Sex   Age  Salary  Spending_Score  NewColumn Customer_Satisfaction
0   1    1  19.0    15.0             NaN          1           Unsatisfied
1   2    1   NaN    15.0            81.0          1             Satisfied
2   3    0  20.0    16.0             6.0          1           Unsatisfied
3   4    0  23.0     NaN            77.0          1             Satisfied
4   5    0   NaN     NaN            40.0          1           Unsatisfied

In [7]:
df = data_frame.drop(columns=(['ID', 'NewColumn']))
df.describe()

              Sex         Age      Salary  Spending_Score
count  200.000000  197.000000  198.000000      199.000000
mean     0.440000   39.000000   61.005051       50.256281
std      0.497633   14.002915   26.017857       25.876350
min      0.000000   18.000000   15.000000        1.000000
25%      0.000000   29.000000   42.250000       34.500000
50%      0.000000   36.000000   62.000000       50.000000
75%      1.000000   49.000000   78.000000       73.000000
max      1.000000   70.000000  137.000000       99.000000

In [ ]:
Salary_fig = px.histogram(df, x='Salary')
Salary_fig.show()

In [ ]:
Age_fig = px.box(df, x='Age')
Age_fig.show()

In [ ]:
Salary_fig = px.box(df, x='Salary')
Salary_fig.show()

In [ ]:
Age_Salary_fig  = px.scatter(df, x='Age', y='Salary')
Age_Salary_fig.show()

## Using IQR to find outliers

*Outliers fall below (q1 - 1.5IQR) and above (q3+ 1.5IQR)*

In [8]:
def find_outliers_IQR(df):
  q1=df.quantile(0.25)
  q3 = df.quantile(0.75)
  IQR=q3-q1
  outliers = df[((df<(q1-1.5*IQR))|(df>(q3+1.5*IQR)))]
  return outliers

In [9]:
outliers = find_outliers_IQR(df['Salary'])
print("numbers of outliers: "+str(len(outliers)))
outliers

numbers of outliers: 2

198    137.0
199    137.0
Name: Salary, dtype: float64

In [10]:
#dropping outliers
df.drop(df.index[[198, 199]], inplace=True)

In [11]:
#To verify we can check for outliers again
outliers = find_outliers_IQR(df['Salary'])
print("number of outliers: "+str(len(outliers)))
outliers

number of outliers: 0

Series([], Name: Salary, dtype: float64)

In [ ]:
df.describe().transpose()

                count       mean        std   min   25%   50%   75%    max
Sex             198.0   0.434343   0.496927   0.0   0.0   0.0   1.0    1.0
Age             195.0  39.082051  14.050844  18.0  28.5  36.0  49.0   70.0
Salary          196.0  60.229592  24.980676  15.0  42.0  61.5  78.0  126.0
Spending_Score  197.0  50.253807  25.799987   1.0  35.0  50.0  73.0   99.0

In [ ]:
text = 'this is me'
print(type(text))

<class 'str'>

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sex                    198 non-null    int64
 1   Age                    195 non-null    float64
 2   Salary                 196 non-null    float64
 3   Spending_Score         197 non-null    float64
 4   Customer_Satisfaction  198 non-null    object
dtypes: float64(3), int64(1), object(1)
memory usage: 7.9+ KB
None

In [ ]:
!git init

Reinitialized existing Git repository in /content/drive/MyDrive/Colab_Notebooks/.git/

In [ ]:
!git add .

In [ ]:
%cd MyDive

[Errno 2] No such file or directory: 'MyDive'
/content

In [ ]:
%ls

'Copy of DataExploringAndPreparing.ipynb'   Mall_Customers.csv
 DataExploringAndPreparing.ipynb            Prepared_Mall_Customers.csv
 diabetes.csv                               Redo_Week1.ipynb
 Loan_Approval_1.ipynb                      slr.csv
 loan_approval_data.csv                     Week_1_tut.ipynb

In [ ]:
%cd drive

[Errno 2] No such file or directory: 'drive'
/content/drive/MyDrive/Colab_Notebooks

In [ ]:
%cd MyDrive

/content/drive/MyDrive

In [ ]:
%cd Colab_Notebooks

/content/drive/MyDrive/Colab_Notebooks

In [ ]:
!git init

Reinitialized existing Git repository in /content/drive/MyDrive/Colab_Notebooks/.git/

In [ ]:
!git add .

In [ ]:
!git commit -m "finished outliers"

[main 5df42ce] finished outliers
 1 file changed, 1 insertion(+), 1 deletion(-)

##Part C : Mitigating Missing Data

In [ ]:
# isnull() finds missng values
df.isnull()

       Sex    Age  Salary  Spending_Score  Customer_Satisfaction
0    False  False   False            True                  False
1    False   True   False           False                  False
2    False  False   False           False                  False
3    False  False    True           False                  False
4    False   True    True           False                  False
..     ...    ...     ...             ...                    ...
193  False  False   False           False                  False
194  False  False   False           False                  False
195  False  False   False           False                  False
196  False  False   False           False                  False
197  False  False   False           False                  False

[198 rows x 5 columns]

In [ ]:
df.isnull().sum()

Sex                      0
Age                      3
Salary                   2
Spending_Score           1
Customer_Satisfaction    0
dtype: int64

In [ ]:
df['Salary'].isnull().sum()

np.int64(2)

In [ ]:
print(len(df))
print(len(data_frame))

198
200

In [ ]:
(df.isnull().sum()/len(df))*100

Sex                      0.000000
Age                      1.515152
Salary                   1.010101
Spending_Score           0.505051
Customer_Satisfaction    0.000000
dtype: float64

In [12]:
df_Complete_Case = data_frame.dropna()
df_Complete_Case

      ID  Sex   Age  Salary  Spending_Score  NewColumn Customer_Satisfaction
2      3    0  20.0    16.0             6.0          1           Unsatisfied
5      6    0  22.0    17.0            76.0          1             Satisfied
7      8    0  23.0    18.0            94.0          1             Satisfied
8      9    1  64.0    19.0             3.0          1           Unsatisfied
9     10    0  30.0    19.0            72.0          1             Satisfied
..   ...  ...   ...     ...             ...        ...                   ...
195  196    0  35.0   120.0            79.0          1             Satisfied
196  197    0  45.0   126.0            28.0          1           Unsatisfied
197  198    1  32.0   126.0            74.0          1             Satisfied
198  199    1  32.0   137.0            18.0          1           Unsatisfied
199  200    1  30.0   137.0            83.0          1             Satisfied

[195 rows x 7 columns]

In [13]:
Mean_Salary = df['Salary'].mean()
Mean_Spending_Score = df['Spending_Score'].mean()
Mean_Age = df['Age'].mean()

df['Salary'].fillna(Mean_Salary, inplace=True)
df['Spending_Score'].fillna(Mean_Spending_Score, inplace=True)
df['Age'].fillna(Mean_Age, inplace=True)

/tmp/ipython-input-1019957238.py:5: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-1019957238.py:6: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-1019957238.py:7: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [16]:
df.isna().sum()

Sex                      0
Age                      0
Salary                   0
Spending_Score           0
Customer_Satisfaction    0
dtype: int64

In [19]:
df.to_csv(r'/content/drive/MyDrive/Colab_Notebooks/Clean_Mall_Customers_tut2.csv', index=False)

#Part D - Data Scaling

2 types of scaling.

-Standard Scaling (Z score)

-Min max scaling (Normalization)

1- Merging data files

In [3]:
# first data file
import pandas as pd
df1 = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Mall_Customers.csv')
df1.head()

   CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male  19.0                15.0                     NaN
1           2    Male   NaN                15.0                    81.0
2           3  Female  20.0                16.0                     6.0
3           4  Female  23.0                 NaN                    77.0
4           5  Female   NaN                 NaN                    40.0

In [4]:
# second data file
df2 = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Mall_Customers_Additional.csv')
df2.head()

   CustomerID  Travel_distance_meters  Dependents
0           1                    5040           5
1           2                    3492           3
2           3                    2795           0
3           4                    6315           0
4           5                    1978           3

In [5]:
# joining df1 and df2 to one dataset.

Merged_Mall_df = df1.merge(df2, on ='CustomerID')
Merged_Mall_df.head()

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Travel_distance_meters,Dependents
0,1,Male,19.0,15.0,NaN,5040,5
1,2,Male,NaN,15.0,81.0,3492,3
2,3,Female,20.0,16.0,6.0,2795,0
3,4,Female,23.0,NaN,77.0,6315,0
4,5,Female,NaN,NaN,40.0,1978,3

In [6]:
# downloading newly created dataset
Merged_Mall_df.to_csv("Merged_Mall_Data.csv", index=False)

2 - Examining Data Magnitude Variations

In [22]:
import pandas as pd
df = pd.read_csv('/content/Merged_Mall_Data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     197 non-null    float64
 3   Annual Income (k$)      198 non-null    float64
 4   Spending Score (1-100)  199 non-null    float64
 5   Travel_distance_meters  200 non-null    int64
 6   Dependents              200 non-null    int64
dtypes: float64(3), int64(3), object(1)
memory usage: 11.1+ KB

3 - Standard Scaling / Z-Score

In [23]:
from sklearn.preprocessing import StandardScaler

# drop unnecessary numeric and non-numeric values
prop_df = df.drop(columns=(['CustomerID', 'Gender']))

scaled_df = StandardScaler().fit_transform(prop_df)
scaled_df

array([[-1.43191295e+00, -1.77269273e+00,             nan,
         4.45914533e-02,  1.36257170e+00],
       [            nan, -1.77269273e+00,  1.19109751e+00,
        -5.10404082e-01,  2.61503659e-01],
       [-1.36031730e+00, -1.73416016e+00, -1.71461193e+00,
        -7.60295483e-01, -1.39009840e+00],
       [-1.14553036e+00,             nan,  1.03612634e+00,
         5.01709869e-01, -1.39009840e+00],
       [            nan,             nan, -3.97356984e-01,
        -1.05320979e+00,  2.61503659e-01],
       [-1.21712600e+00, -1.69562759e+00,  9.97383551e-01,
         1.05316498e-02, -1.39009840e+00],
       [            nan, -1.65709503e+00, -1.71461193e+00,
        -1.77693580e-01, -1.39009840e+00],
       [-1.14553036e+00, -1.65709503e+00,  1.69475382e+00,
         8.02870237e-01, -2.89030360e-01],
       [ 1.78989118e+00, -1.61856246e+00, -1.83084031e+00,
        -9.20062851e-02, -1.39009840e+00],
       [-6.44360826e-01, -1.61856246e+00,  8.42412380e-01,
         1.53582825e-01,  1.36257170e+00],
       [ 2.00467813e+00, -1.61856246e+00, -1.40466959e+00,
         5.48318021e-01,  2.61503659e-01],
       [-2.86382589e-01, -1.61856246e+00,  1.88846778e+00,
        -3.83845023e-01,  1.36257170e+00],
       [ 1.36031730e+00, -1.58002989e+00, -1.36592680e+00,
        -9.95352943e-02,  2.61503659e-01],
       [-1.07393471e+00, -1.58002989e+00,  1.03612634e+00,
        -6.62776887e-01,  1.36257170e+00],
       [-1.43191295e-01, -1.58002989e+00, -1.44341238e+00,
         8.09323674e-01, -8.39564379e-01],
       [-1.21712600e+00, -1.58002989e+00,  1.11361193e+00,
         8.34061847e-01, -2.89030360e-01],
       [-2.86382589e-01, -1.54149732e+00, -5.91070947e-01,
        -9.99431156e-01,  8.12037678e-01],
       [-1.36031730e+00, -1.54149732e+00,  6.09955624e-01,
        -5.01799500e-01, -8.39564379e-01],
       [ 9.30743416e-01, -1.46443219e+00, -8.23527702e-01,
         1.27934896e+00, -2.89030360e-01],
       [-2.86382589e-01, -1.46443219e+00,  1.84972499e+00,
        -3.45482928e-01, -8.39564379e-01],
       [-2.86382589e-01, -1.42589962e+00, -5.91070947e-01,
         1.10152094e+00, -8.39564379e-01],
       [-1.00233906e+00, -1.42589962e+00,  8.81155173e-01,
         9.27995200e-01, -8.39564379e-01],
       [ 5.01169531e-01, -1.38736705e+00, -1.75335473e+00,
         1.05240311e+00,  1.36257170e+00],
       [-5.72765179e-01, -1.38736705e+00,  8.81155173e-01,
         8.36571517e-01,  2.61503659e-01],
       [ 1.07393471e+00, -1.27176935e+00, -1.40466959e+00,
         2.79783360e-01, -1.39009840e+00],
       [-7.15956473e-01, -1.27176935e+00,  1.22984031e+00,
        -1.23139634e+00,  1.36257170e+00],
       [ 4.29573884e-01, -1.27176935e+00, -7.07299324e-01,
        -7.40800727e-02,  1.36257170e+00],
       [-2.86382589e-01, -1.27176935e+00,  4.16241661e-01,
         1.75905441e+00, -8.39564379e-01],
       [ 7.15956473e-02, -1.23323678e+00, -7.46042117e-01,
        -1.47447578e+00,  2.61503659e-01],
       [-1.14553036e+00, -1.23323678e+00,  1.42355427e+00,
         1.66404548e+00,  1.36257170e+00],
       [ 1.50350859e+00, -1.19470421e+00, -1.79209752e+00,
        -9.84014613e-01,  1.36257170e+00],
       [-1.28872165e+00, -1.19470421e+00,  8.81155173e-01,
        -1.25003961e+00,  1.36257170e+00],
       [ 1.00233906e+00, -1.07910651e+00, -1.79209752e+00,
        -3.06986387e-02, -2.89030360e-01],
       [-1.50350859e+00, -1.07910651e+00,  1.61726823e+00,
        -9.21989919e-01, -1.39009840e+00],
       [ 7.15956473e-01, -1.07910651e+00, -1.40466959e+00,
        -7.12611758e-01,  2.61503659e-01],
       [-1.28872165e+00, -1.07910651e+00,  1.19109751e+00,
         1.68806660e+00, -1.39009840e+00],
       [ 2.14786942e-01, -1.04057394e+00, -1.28844121e+00,
         1.26966881e+00, -2.89030360e-01],
       [-6.44360826e-01, -1.04057394e+00,  8.81155173e-01,
         8.25457265e-01, -1.39009840e+00],
       [-2.14786942e-01, -9.24976237e-01, -9.39756080e-01,
        -7.07592418e-01,  8.12037678e-01],
       [-1.36031730e+00, -9.24976237e-01,  9.58640758e-01,
         9.08410813e-02, -1.39009840e+00],
       [ 1.86148683e+00, -8.86443669e-01, -5.91070947e-01,
         1.20979526e+00, -2.89030360e-01],
       [-1.07393471e+00, -8.86443669e-01,  1.61726823e+00,
        -9.57125295e-01,  8.12037678e-01],
       [ 6.44360826e-01, -8.47911101e-01, -5.52328154e-01,
        -9.02271085e-01, -1.39009840e+00],
       [-5.72765179e-01, -8.47911101e-01,  4.16241661e-01,
        -1.74825386e-01,  8.12037678e-01],
       [ 7.15956473e-01, -8.47911101e-01, -8.62270495e-01,
         1.23596753e+00, -1.39009840e+00],
       [-1.07393471e+00, -8.47911101e-01,  5.71212832e-01,
         4.28570923e-01, -2.89030360e-01],
       [ 7.87552121e-01, -8.09378533e-01,  1.83784906e-01,
        -1.41998010e+00, -2.89030360e-01],
       [-8.59147768e-01, -8.09378533e-01, -1.26157435e-01,
        -7.33764689e-01,  2.61503659e-01],
       [-7.15956473e-01, -8.09378533e-01, -3.19871398e-01,
        -1.64405775e+00,  8.12037678e-01],
       [-5.72765179e-01, -8.09378533e-01, -3.19871398e-01,
        -1.69998754e+00,  8.12037678e-01],
       [ 7.15956473e-01, -7.32313398e-01,  6.75565278e-02,
        -9.68239547e-01, -2.89030360e-01],
       [-4.29573884e-01, -7.32313398e-01,  3.77498869e-01,
         1.10474765e+00, -1.39009840e+00],
       [-5.72765179e-01, -6.93780830e-01,  1.45042113e-01,
         1.23242710e-02,  2.61503659e-01],
       [ 1.43191295e+00, -6.93780830e-01,  3.77498869e-01,
         1.22915557e+00,  8.12037678e-01],
       [ 7.87552121e-01, -6.93780830e-01, -2.03643020e-01,
         7.26146048e-01, -1.39009840e+00],
       [ 5.72765179e-01, -6.93780830e-01, -3.58614191e-01,
         4.36458456e-01, -2.89030360e-01],
       [ 8.59147768e-01, -6.55248262e-01, -9.92905740e-03,
         1.78666077e+00, -8.39564379e-01],
       [ 2.14786942e+00, -6.55248262e-01, -1.64900228e-01,
         8.31193653e-01, -8.39564379e-01],
       [-8.59147768e-01, -5.78183126e-01,  2.88137352e-02,
        -1.48164627e+00, -1.39009840e+00],
       [ 1.00233906e+00, -5.78183126e-01, -1.64900228e-01,
        -2.01669889e-03, -1.39009840e+00],
       [ 2.21946507e+00, -5.78183126e-01,  2.22527698e-01,
         7.45147833e-01,  2.61503659e-01],
       [-1.43191295e+00, -5.78183126e-01,  1.83784906e-01,
         6.71291838e-01, -1.39009840e+00],
       [ 2.00467813e+00, -5.39650558e-01,  6.75565278e-02,
        -2.97440679e-01,  8.12037678e-01],
       [ 1.07393471e+00, -5.39650558e-01,  3.38756076e-01,
         1.29870927e+00, -1.39009840e+00],
       [ 1.71829554e+00, -5.01117991e-01,  2.88137352e-02,
         1.82072058e+00,  2.61503659e-01],
       [-1.50350859e+00, -5.01117991e-01,  3.38756076e-01,
         5.14258218e-01, -1.39009840e+00],
       [ 2.86382589e-01, -5.01117991e-01, -9.92905740e-03,
        -7.38066980e-01,  1.36257170e+00],
       [ 2.07627377e+00, -5.01117991e-01, -8.74146426e-02,
        -5.68709088e-02, -2.89030360e-01],
       [-1.43191295e+00, -5.01117991e-01,  3.38756076e-01,
         1.38883330e-01, -8.39564379e-01],
       [-5.01169531e-01, -5.01117991e-01, -1.26157435e-01,
        -1.09121336e+00,  1.36257170e+00],
       [ 2.21946507e+00, -4.62585423e-01,  1.83784906e-01,
         9.72945177e-02, -8.39564379e-01],
       [ 5.72765179e-01, -4.62585423e-01, -3.19871398e-01,
        -7.23367485e-01,  8.12037678e-01],
       [ 1.50350859e+00, -4.24052855e-01, -4.86718500e-02,
         1.46291338e+00, -8.39564379e-01],
       [ 1.50350859e+00, -4.24052855e-01,  2.22527698e-01,
        -9.74692983e-01,  1.36257170e+00],
       [ 1.43191295e+00, -2.69922584e-01, -1.26157435e-01,
        -5.49124701e-01, -2.89030360e-01],
       [-9.30743416e-01, -2.69922584e-01,  1.45042113e-01,
         1.66489698e-01, -1.39009840e+00],
       [ 4.29573884e-01, -2.69922584e-01,  1.06299320e-01,
         4.55101717e-01,  8.12037678e-01],
       [ 7.15956473e-02, -2.69922584e-01, -8.74146426e-02,
        -1.01233803e+00,  8.12037678e-01],
       [-1.14553036e+00, -2.69922584e-01,  6.75565278e-02,
        -1.22422586e+00, -8.39564379e-01],
       [ 7.15956473e-01, -2.69922584e-01, -3.19871398e-01,
         1.67695235e+00,  1.36257170e+00],
       [ 1.28872165e+00, -2.69922584e-01,  2.88137352e-02,
         8.39798235e-01, -1.39009840e+00],
       [-7.15956473e-02, -2.69922584e-01,  1.83784906e-01,
         7.84226976e-01,  1.36257170e+00],
       [ 2.00467813e+00, -2.69922584e-01, -3.58614191e-01,
         1.72463608e+00, -1.39009840e+00],
       [ 5.01169531e-01, -2.69922584e-01, -2.42385813e-01,
        -4.44077096e-01, -2.89030360e-01],
       [-1.28872165e+00, -2.69922584e-01,  2.61270491e-01,
        -1.06826781e+00, -1.39009840e+00],
       [ 6.44360826e-01, -2.69922584e-01, -1.64900228e-01,
        -1.65337938e+00,  2.61503659e-01],
       [ 1.14553036e+00, -1.54324880e-01,  3.00013284e-01,
         1.81964500e+00,  1.36257170e+00],
       [-1.21712600e+00, -1.54324880e-01,  1.83784906e-01,
         9.48789606e-01, -1.39009840e+00],
       [-3.57978237e-01, -1.15792312e-01,  3.77498869e-01,
        -1.21347013e+00,  1.36257170e+00],
       [ 7.87552121e-01, -1.15792312e-01, -1.64900228e-01,
         7.63432570e-01, -1.39009840e+00],
       [ 2.07627377e+00, -7.72597446e-02,  1.83784906e-01,
        -5.26896198e-01,  1.36257170e+00],
       [-1.50350859e+00, -7.72597446e-02, -3.58614191e-01,
         1.37830165e+00,  1.36257170e+00],
       [ 6.44360826e-01, -3.87271768e-02, -4.86718500e-02,
         2.79783360e-01, -1.39009840e+00],
       [ 7.15956473e-02, -3.87271768e-02, -3.97356984e-01,
        -4.34755466e-01, -8.39564379e-01],
       [-5.01169531e-01, -3.87271768e-02, -3.19871398e-01,
         6.17871725e-01,  2.61503659e-01],
       [-1.07393471e+00, -3.87271768e-02,  6.75565278e-02,
        -1.65553053e+00, -2.89030360e-01],
       [ 5.72765179e-01, -3.87271768e-02, -1.26157435e-01,
         3.37864288e-01,  8.12037678e-01],
       [-8.59147768e-01, -3.87271768e-02, -9.92905740e-03,
        -2.36133033e-01,  8.12037678e-01],
       [ 6.44360826e-01, -1.94608928e-04, -3.19871398e-01,
         5.10314451e-01,  2.61503659e-01],
       [-1.36031730e+00, -1.94608928e-04, -4.86718500e-02,
         1.32165482e+00,  2.61503659e-01],
       [-1.14553036e+00,  3.83379589e-02, -3.58614191e-01,
         1.11586191e+00,  8.12037678e-01],
       [ 7.15956473e-01,  3.83379589e-02, -8.74146426e-02,
         1.17358431e+00, -1.39009840e+00],
       [ 2.00467813e+00,  3.83379589e-02,  3.38756076e-01,
        -1.27800450e+00, -1.39009840e+00],
       [-9.30743416e-01,  3.83379589e-02,  1.83784906e-01,
         9.10427512e-01,  8.12037678e-01],
       [ 7.15956473e-01,  3.83379589e-02,  2.22527698e-01,
        -9.67881022e-01, -8.39564379e-01],
       [-1.28872165e+00,  3.83379589e-02, -3.19871398e-01,
        -1.24860551e+00, -8.39564379e-01],
       [ 1.93308248e+00,  7.68705267e-02, -9.92905740e-03,
         3.41808055e-01,  8.12037678e-01],
       [ 1.07393471e+00,  7.68705267e-02, -1.64900228e-01,
        -8.40963439e-01,  1.36257170e+00],
       [ 2.07627377e+00,  7.68705267e-02, -2.81128606e-01,
        -1.01126246e+00, -1.39009840e+00],
       [ 1.93308248e+00,  7.68705267e-02, -8.74146426e-02,
         1.48263221e+00,  2.61503659e-01],
       [ 1.86148683e+00,  7.68705267e-02,  6.75565278e-02,
         1.71316330e+00, -1.39009840e+00],
       [-1.43191295e+00,  7.68705267e-02,  1.45042113e-01,
         3.05955630e-01,  8.12037678e-01],
       [-7.15956473e-02,  1.15403095e-01, -3.19871398e-01,
         1.32788418e-01,  1.36257170e+00],
       [-1.43191295e+00,  1.15403095e-01, -1.64900228e-01,
         5.88831261e-01,  2.61503659e-01],
       [-1.50350859e+00,  1.53935662e-01, -8.74146426e-02,
        -4.07866147e-01,  2.61503659e-01],
       [-1.43191295e+00,  1.53935662e-01, -9.92905740e-03,
        -1.67524936e+00,  1.36257170e+00],
       [ 1.71829554e+00,  1.53935662e-01, -2.81128606e-01,
        -8.26622469e-01,  2.61503659e-01],
       [ 7.15956473e-01,  1.53935662e-01,  3.38756076e-01,
         5.04219539e-01,  2.61503659e-01],
       [ 8.59147768e-01,  2.31000798e-01, -2.81128606e-01,
        -8.66060136e-01,  2.61503659e-01],
       [ 7.87552121e-01,  2.31000798e-01,  2.61270491e-01,
        -1.30453529e+00,  1.36257170e+00],
       [-8.59147768e-01,  2.31000798e-01,  2.22527698e-01,
         5.53337361e-01,  2.61503659e-01],
       [-7.15956473e-02,  2.31000798e-01, -3.97356984e-01,
        -5.50558798e-01, -8.39564379e-01],
       [ 7.15956473e-02,  3.08065934e-01,  3.00013284e-01,
         1.69129332e+00,  1.36257170e+00],
       [ 0.00000000e+00,  3.08065934e-01,  1.57852544e+00,
         1.79992617e+00, -2.89030360e-01],
       [-1.14553036e+00,  3.46598501e-01, -8.23527702e-01,
         1.06495146e+00, -1.39009840e+00],
       [-5.72765179e-01,  3.46598501e-01,  1.03612634e+00,
        -5.98601047e-01,  8.12037678e-01],
       [ 2.86382589e-01,  3.85131069e-01, -5.91070947e-01,
        -1.27724263e-02, -2.89030360e-01],
       [ 7.15956473e-02,  3.85131069e-01,  1.73349661e+00,
        -1.50638444e+00, -8.39564379e-01],
       [ 1.43191295e+00,  3.85131069e-01, -1.52089797e+00,
        -6.84288342e-01,  8.12037678e-01],
       [-7.15956473e-02,  3.85131069e-01,  9.58640758e-01,
        -9.50671858e-01,  2.61503659e-01],
       [ 5.72765179e-01,  3.85131069e-01, -1.59838355e+00,
         1.01260692e+00, -1.39009840e+00],
       [ 0.00000000e+00,  3.85131069e-01,  9.58640758e-01,
        -1.47124907e+00, -8.39564379e-01],
       [-1.00233906e+00,  4.23663637e-01, -6.29813739e-01,
        -1.05392684e+00,  8.12037678e-01],
       [-5.72765179e-01,  4.23663637e-01,  8.03669587e-01,
        -1.21777242e+00, -8.39564379e-01],
       [-1.36031730e+00,  4.62196205e-01, -1.75335473e+00,
        -1.35652131e+00,  8.12037678e-01],
       [-7.15956473e-01,  4.62196205e-01,  1.46229706e+00,
        -1.25183223e+00,  1.36257170e+00],
       [ 3.57978237e-01,  4.62196205e-01, -1.67586914e+00,
        -4.42642999e-01, -2.89030360e-01],
       [-5.01169531e-01,  4.62196205e-01,  8.81155173e-01,
         1.01224840e+00,  1.36257170e+00],
       [-1.43191295e+00,  5.00728773e-01, -1.55964076e+00,
        -1.03958587e+00, -1.39009840e+00],
       [-2.86382589e-01,  5.00728773e-01,  8.42412380e-01,
        -1.69676082e+00, -1.39009840e+00],
       [ 1.28872165e+00,  5.39261341e-01, -1.75335473e+00,
         2.73688448e-01, -2.89030360e-01],
       [-5.01169531e-01,  5.39261341e-01,  1.65601102e+00,
         9.68149916e-01,  8.12037678e-01],
       [-7.87552121e-01,  5.77793908e-01, -3.97356984e-01,
        -6.97553740e-01,  2.61503659e-01],
       [-5.01169531e-01,  5.77793908e-01,  1.42355427e+00,
        -1.06683371e+00, -2.89030360e-01],
       [-1.00233906e+00,  6.16326476e-01, -1.48215518e+00,
         1.02874051e+00, -2.89030360e-01],
       [-7.87552121e-01,  6.16326476e-01,  1.81098220e+00,
         8.75650660e-01,  8.12037678e-01],
       [ 6.44360826e-01,  6.16326476e-01, -5.52328154e-01,
         2.82651554e-01,  2.61503659e-01],
       [-5.01169531e-01,  6.16326476e-01,  9.19897965e-01,
         2.31741111e-01, -1.39009840e+00],
       [-3.57978237e-01,  6.54859044e-01, -1.09472725e+00,
         1.24134539e+00,  2.61503659e-01],
       [-3.57978237e-01,  6.54859044e-01,  1.53978265e+00,
        -1.60354451e+00,  1.36257170e+00],
       [ 2.86382589e-01,  6.54859044e-01, -1.28844121e+00,
        -2.06599598e-02,  1.36257170e+00],
       [ 0.00000000e+00,  6.54859044e-01,  1.46229706e+00,
        -1.07041896e+00,  2.61503659e-01],
       [ 3.57978237e-01,  6.54859044e-01, -1.17221284e+00,
         6.10342716e-01,  2.61503659e-01],
       [-7.15956473e-02,  6.54859044e-01,  9.97383551e-01,
         1.30838943e+00, -2.89030360e-01],
       [ 5.72765179e-01,  6.54859044e-01, -1.32718401e+00,
         7.99643519e-01,  8.12037678e-01],
       [-8.59147768e-01,  6.54859044e-01,  1.50103985e+00,
        -4.76344279e-01, -2.89030360e-01],
       [-1.43191295e-01,  6.54859044e-01, -1.90832590e+00,
        -4.70607891e-01,  8.12037678e-01],
       [-6.44360826e-01,  6.54859044e-01,  1.07486914e+00,
        -1.50889411e+00, -1.39009840e+00],
       [-3.57978237e-01,  6.54859044e-01, -1.90832590e+00,
         2.47874702e-01, -2.89030360e-01],
       [-6.44360826e-01,  6.54859044e-01,  8.81155173e-01,
         1.21589017e+00,  8.12037678e-01],
       [ 1.21712600e+00,  6.93391612e-01, -5.91070947e-01,
         1.19903953e+00, -2.89030360e-01],
       [-7.15956473e-01,  6.93391612e-01,  1.26858310e+00,
         9.34090112e-01,  1.36257170e+00],
       [-1.43191295e+00,  7.70456748e-01, -1.75335473e+00,
         1.78271701e+00, -8.39564379e-01],
       [-5.72765179e-01,  7.70456748e-01,  1.65601102e+00,
         1.62819306e+00,  1.36257170e+00],
       [ 7.87552121e-01,  9.24587019e-01, -9.39756080e-01,
        -1.23032077e+00, -1.39009840e+00],
       [-2.14786942e-01,  9.24587019e-01,  9.58640758e-01,
        -9.09307123e-02,  8.12037678e-01],
       [ 2.14786942e-01,  9.63119587e-01, -1.17221284e+00,
        -1.28087269e+00, -1.39009840e+00],
       [-4.29573884e-01,  9.63119587e-01,  1.73349661e+00,
         1.80606590e-02,  1.36257170e+00],
       [-2.14786942e-01,  1.00165215e+00, -9.01013288e-01,
         2.27080295e-01, -8.39564379e-01],
       [-5.01169531e-01,  1.00165215e+00,  4.93727247e-01,
        -1.38842996e+00, -2.89030360e-01],
       [ 7.15956473e-02,  1.00165215e+00, -1.44341238e+00,
        -8.75740291e-01,  1.36257170e+00],
       [-7.87552121e-01,  1.00165215e+00,  9.58640758e-01,
        -1.65660610e+00,  1.36257170e+00],
       [-2.14786942e-01,  1.00165215e+00, -1.55964076e+00,
         1.45336767e-01,  1.36257170e+00],
       [-2.14786942e-01,  1.00165215e+00,  1.61726823e+00,
        -3.61257995e-01,  1.36257170e+00],
       [ 9.30743416e-01,  1.04018472e+00, -1.44341238e+00,
         2.34250780e-01,  2.61503659e-01],
       [-6.44360826e-01,  1.04018472e+00,  1.38481148e+00,
         1.12231534e+00,  1.36257170e+00],
       [ 1.36031730e+00,  1.04018472e+00, -1.36592680e+00,
        -4.77061327e-01, -8.39564379e-01],
       [-8.59147768e-01,  1.04018472e+00,  7.26184002e-01,
        -7.24084534e-01,  1.36257170e+00],
       [ 1.43191295e+00,  1.23284756e+00, -1.40466959e+00,
        -6.06488581e-01, -1.39009840e+00],
       [-2.86382589e-01,  1.23284756e+00,  1.53978265e+00,
         9.86793176e-01,  8.12037678e-01],
       [-1.43191295e-01,  1.38697783e+00, -7.07299324e-01,
        -8.37378196e-01,  2.61503659e-01],
       [-5.01169531e-01,  1.38697783e+00,  1.38481148e+00,
        -1.03313244e+00,  8.12037678e-01],
       [ 5.01169531e-01,  1.42551040e+00, -1.36592680e+00,
        -1.48630708e+00,  1.36257170e+00],
       [-7.15956473e-01,  1.42551040e+00,  1.46229706e+00,
         1.71150513e-01, -8.39564379e-01],
       [ 1.43191295e-01,  1.46404297e+00, -4.36099776e-01,
        -1.13029251e+00,  1.36257170e+00],
       [-6.44360826e-01,  1.46404297e+00,  1.81098220e+00,
        -4.76344279e-01, -2.89030360e-01],
       [ 1.07393471e+00,  1.54110810e+00, -1.01724167e+00,
         1.92303443e-01,  2.61503659e-01],
       [-7.87552121e-01,  1.54110810e+00,  6.87441210e-01,
        -1.05571946e+00, -1.39009840e+00],
       [ 1.43191295e-01,  1.61817324e+00, -1.28844121e+00,
         5.00275772e-01, -2.89030360e-01],
       [-2.14786942e-01,  1.61817324e+00,  1.34606868e+00,
         9.19032094e-01, -1.39009840e+00],
       [-3.57978237e-01,  1.61817324e+00, -1.05598446e+00,
         1.44391159e+00,  8.12037678e-01],
       [-5.01169531e-01,  1.61817324e+00,  7.26184002e-01,
         7.35826203e-01, -2.89030360e-01],
       [-4.29573884e-01,  2.00349892e+00, -1.63712635e+00,
         2.85161224e-01,  8.12037678e-01],
       [-7.15956473e-02,  2.00349892e+00,  1.57852544e+00,
        -1.59243026e+00, -1.39009840e+00],
       [ 5.72765179e-01,  2.27322689e+00, -1.32718401e+00,
         3.65112131e-01, -8.39564379e-01],
       [-2.86382589e-01,  2.27322689e+00,  1.11361193e+00,
        -1.29664776e+00, -2.89030360e-01],

In [25]:
scaled_df = pd.DataFrame(scaled_df,columns = prop_df.columns)

In [26]:
scaled_df.head()

,Age,Annual Income (k$),Spending Score (1-100),Travel_distance_meters,Dependents
0,-1.431913,-1.772693,NaN,0.044591,1.362572
1,NaN,-1.772693,1.191098,-0.510404,0.261504
2,-1.360317,-1.734160,-1.714612,-0.760295,-1.390098
3,-1.145530,NaN,1.036126,0.501710,-1.390098
4,NaN,NaN,-0.397357,-1.053210,0.261504

In [27]:
scaled_df.describe()

,Age,Annual Income (k$),Spending Score (1-100),Travel_distance_meters,Dependents
count,1.970000e+02,198.000000,1.990000e+02,2.000000e+02,2.000000e+02
mean,9.017040e-18,0.000000,5.802171e-17,-8.881784e-18,7.105427e-17
std,1.002548e+00,1.002535,1.002522e+00,1.002509e+00,1.002509e+00
min,-1.503509e+00,-1.772693,-1.908326e+00,-1.699988e+00,-1.390098e+00
25%,-7.159565e-01,-0.722680,-6.104423e-01,-9.291604e-01,-8.395644e-01
50%,-2.147869e-01,0.038338,-9.929057e-03,1.519246e-02,2.615037e-01
75%,7.159565e-01,0.654859,8.811552e-01,8.346893e-01,8.120377e-01
max,2.219465e+00,2.928281,1.888468e+00,1.820721e+00,1.362572e+00

# Min max scaling

In [28]:
from sklearn.preprocessing import MinMaxScaler

df_mms = MinMaxScaler().fit_transform(scaled_df)
df_mms

array([[1.92307692e-02, 0.00000000e+00,            nan, 4.95519348e-01,
        1.00000000e+00],
       [           nan, 0.00000000e+00, 8.16326531e-01, 3.37881874e-01,
        6.00000000e-01],
       [3.84615385e-02, 8.19672131e-03, 5.10204082e-02, 2.66904277e-01,
        0.00000000e+00],
       [9.61538462e-02,            nan, 7.75510204e-01, 6.25356415e-01,
        0.00000000e+00],
       [           nan,            nan, 3.97959184e-01, 1.83706721e-01,
        6.00000000e-01],
       [7.69230769e-02, 1.63934426e-02, 7.65306122e-01, 4.85845214e-01,
        0.00000000e+00],
       [           nan, 2.45901639e-02, 5.10204082e-02, 4.32382892e-01,
        0.00000000e+00],
       [9.61538462e-02, 2.45901639e-02, 9.48979592e-01, 7.10896130e-01,
        4.00000000e-01],
       [8.84615385e-01, 3.27868852e-02, 2.04081633e-02, 4.56720978e-01,
        0.00000000e+00],
       [2.30769231e-01, 3.27868852e-02, 7.24489796e-01, 5.26476578e-01,
        1.00000000e+00],
       [9.42307692e-01, 3.27868852e-02, 1.32653061e-01, 6.38594705e-01,
        6.00000000e-01],
       [3.26923077e-01, 3.27868852e-02, 1.00000000e+00, 3.73828921e-01,
        1.00000000e+00],
       [7.69230769e-01, 4.09836066e-02, 1.42857143e-01, 4.54582485e-01,
        6.00000000e-01],
       [1.15384615e-01, 4.09836066e-02, 7.75510204e-01, 2.94602851e-01,
        1.00000000e+00],
       [3.65384615e-01, 4.09836066e-02, 1.22448980e-01, 7.12729124e-01,
        2.00000000e-01],
       [7.69230769e-02, 4.09836066e-02, 7.95918367e-01, 7.19755601e-01,
        4.00000000e-01],
       [3.26923077e-01, 4.91803279e-02, 3.46938776e-01, 1.98981670e-01,
        8.00000000e-01],
       [3.84615385e-02, 4.91803279e-02, 6.63265306e-01, 3.40325866e-01,
        2.00000000e-01],
       [6.53846154e-01, 6.55737705e-02, 2.85714286e-01, 8.46232179e-01,
        4.00000000e-01],
       [3.26923077e-01, 6.55737705e-02, 9.89795918e-01, 3.84725051e-01,
        2.00000000e-01],
       [3.26923077e-01, 7.37704918e-02, 3.46938776e-01, 7.95723014e-01,
        2.00000000e-01],
       [1.34615385e-01, 7.37704918e-02, 7.34693878e-01, 7.46435845e-01,
        2.00000000e-01],
       [5.38461538e-01, 8.19672131e-02, 4.08163265e-02, 7.81771894e-01,
        1.00000000e+00],
       [2.50000000e-01, 8.19672131e-02, 7.34693878e-01, 7.20468432e-01,
        6.00000000e-01],
       [6.92307692e-01, 1.06557377e-01, 1.32653061e-01, 5.62321792e-01,
        0.00000000e+00],
       [2.11538462e-01, 1.06557377e-01, 8.26530612e-01, 1.33095723e-01,
        1.00000000e+00],
       [5.19230769e-01, 1.06557377e-01, 3.16326531e-01, 4.61812627e-01,
        1.00000000e+00],
       [3.26923077e-01, 1.06557377e-01, 6.12244898e-01, 9.82484725e-01,
        2.00000000e-01],
       [4.23076923e-01, 1.14754098e-01, 3.06122449e-01, 6.40529532e-02,
        6.00000000e-01],
       [9.61538462e-02, 1.14754098e-01, 8.77551020e-01, 9.55498982e-01,
        1.00000000e+00],
       [8.07692308e-01, 1.22950820e-01, 3.06122449e-02, 2.03360489e-01,
        1.00000000e+00],
       [5.76923077e-02, 1.22950820e-01, 7.34693878e-01, 1.27800407e-01,
        1.00000000e+00],
       [6.73076923e-01, 1.47540984e-01, 3.06122449e-02, 4.74134420e-01,
        4.00000000e-01],
       [0.00000000e+00, 1.47540984e-01, 9.28571429e-01, 2.20977597e-01,
        0.00000000e+00],
       [5.96153846e-01, 1.47540984e-01, 1.32653061e-01, 2.80448065e-01,
        6.00000000e-01],
       [5.76923077e-02, 1.47540984e-01, 8.16326531e-01, 9.62321792e-01,
        0.00000000e+00],
       [4.61538462e-01, 1.55737705e-01, 1.63265306e-01, 8.43482688e-01,
        4.00000000e-01],
       [2.30769231e-01, 1.55737705e-01, 7.34693878e-01, 7.17311609e-01,
        0.00000000e+00],
       [3.46153846e-01, 1.80327869e-01, 2.55102041e-01, 2.81873727e-01,
        8.00000000e-01],
       [3.84615385e-02, 1.80327869e-01, 7.55102041e-01, 5.08655804e-01,
        0.00000000e+00],
       [9.03846154e-01, 1.88524590e-01, 3.46938776e-01, 8.26476578e-01,
        4.00000000e-01],
       [1.15384615e-01, 1.88524590e-01, 9.28571429e-01, 2.10997963e-01,
        8.00000000e-01],
       [5.76923077e-01, 1.96721311e-01, 3.57142857e-01, 2.26578411e-01,
        0.00000000e+00],
       [2.50000000e-01, 1.96721311e-01, 6.12244898e-01, 4.33197556e-01,
        8.00000000e-01],
       [5.96153846e-01, 1.96721311e-01, 2.75510204e-01, 8.33910387e-01,
        0.00000000e+00],
       [1.15384615e-01, 1.96721311e-01, 6.53061224e-01, 6.04582485e-01,
        4.00000000e-01],
       [6.15384615e-01, 2.04918033e-01, 5.51020408e-01, 7.95315682e-02,
        4.00000000e-01],
       [1.73076923e-01, 2.04918033e-01, 4.69387755e-01, 2.74439919e-01,
        6.00000000e-01],
       [2.11538462e-01, 2.04918033e-01, 4.18367347e-01, 1.58859470e-02,
        8.00000000e-01],
       [2.50000000e-01, 2.04918033e-01, 4.18367347e-01, 0.00000000e+00,
        8.00000000e-01],
       [5.96153846e-01, 2.21311475e-01, 5.20408163e-01, 2.07841141e-01,
        4.00000000e-01],
       [2.88461538e-01, 2.21311475e-01, 6.02040816e-01, 7.96639511e-01,
        0.00000000e+00],
       [2.50000000e-01, 2.29508197e-01, 5.40816327e-01, 4.86354379e-01,
        6.00000000e-01],
       [7.88461538e-01, 2.29508197e-01, 6.02040816e-01, 8.31975560e-01,
        8.00000000e-01],
       [6.15384615e-01, 2.29508197e-01, 4.48979592e-01, 6.89103870e-01,
        0.00000000e+00],
       [5.57692308e-01, 2.29508197e-01, 4.08163265e-01, 6.06822811e-01,
        4.00000000e-01],
       [6.34615385e-01, 2.37704918e-01, 5.00000000e-01, 9.90325866e-01,
        2.00000000e-01],
       [9.80769231e-01, 2.37704918e-01, 4.59183673e-01, 7.18940937e-01,
        2.00000000e-01],
       [1.73076923e-01, 2.54098361e-01, 5.10204082e-01, 6.20162933e-02,
        0.00000000e+00],
       [6.73076923e-01, 2.54098361e-01, 4.59183673e-01, 4.82281059e-01,
        0.00000000e+00],
       [1.00000000e+00, 2.54098361e-01, 5.61224490e-01, 6.94501018e-01,
        6.00000000e-01],
       [1.92307692e-02, 2.54098361e-01, 5.51020408e-01, 6.73523422e-01,
        0.00000000e+00],
       [9.42307692e-01, 2.62295082e-01, 5.20408163e-01, 3.98370672e-01,
        8.00000000e-01],
       [6.92307692e-01, 2.62295082e-01, 5.91836735e-01, 8.51731161e-01,
        0.00000000e+00],
       [8.65384615e-01, 2.70491803e-01, 5.10204082e-01, 1.00000000e+00,
        6.00000000e-01],
       [0.00000000e+00, 2.70491803e-01, 5.91836735e-01, 6.28920570e-01,
        0.00000000e+00],
       [4.80769231e-01, 2.70491803e-01, 5.00000000e-01, 2.73217923e-01,
        1.00000000e+00],
       [9.61538462e-01, 2.70491803e-01, 4.79591837e-01, 4.66700611e-01,
        4.00000000e-01],
       [1.92307692e-02, 2.70491803e-01, 5.91836735e-01, 5.22301426e-01,
        2.00000000e-01],
       [2.69230769e-01, 2.70491803e-01, 4.69387755e-01, 1.72912424e-01,
        1.00000000e+00],
       [1.00000000e+00, 2.78688525e-01, 5.51020408e-01, 5.10488798e-01,
        2.00000000e-01],
       [5.57692308e-01, 2.78688525e-01, 4.18367347e-01, 2.77393075e-01,
        8.00000000e-01],
       [8.07692308e-01, 2.86885246e-01, 4.89795918e-01, 8.98370672e-01,
        2.00000000e-01],
       [8.07692308e-01, 2.86885246e-01, 5.61224490e-01, 2.06008147e-01,
        1.00000000e+00],
       [7.88461538e-01, 3.19672131e-01, 4.69387755e-01, 3.26883910e-01,
        4.00000000e-01],
       [1.53846154e-01, 3.19672131e-01, 5.40816327e-01, 5.30142566e-01,
        0.00000000e+00],
       [5.19230769e-01, 3.19672131e-01, 5.30612245e-01, 6.12118126e-01,
        8.00000000e-01],
       [4.23076923e-01, 3.19672131e-01, 4.79591837e-01, 1.95315682e-01,
        8.00000000e-01],
       [9.61538462e-02, 3.19672131e-01, 5.20408163e-01, 1.35132383e-01,
        2.00000000e-01],
       [5.96153846e-01, 3.19672131e-01, 4.18367347e-01, 9.59164969e-01,
        1.00000000e+00],
       [7.50000000e-01, 3.19672131e-01, 5.10204082e-01, 7.21384929e-01,
        0.00000000e+00],
       [3.84615385e-01, 3.19672131e-01, 5.51020408e-01, 7.05600815e-01,
        1.00000000e+00],
       [9.42307692e-01, 3.19672131e-01, 4.08163265e-01, 9.72708758e-01,
        0.00000000e+00],
       [5.38461538e-01, 3.19672131e-01, 4.38775510e-01, 3.56720978e-01,
        4.00000000e-01],
       [5.76923077e-02, 3.19672131e-01, 5.71428571e-01, 1.79429735e-01,
        0.00000000e+00],
       [5.76923077e-01, 3.19672131e-01, 4.59183673e-01, 1.32382892e-02,
        6.00000000e-01],
       [7.11538462e-01, 3.44262295e-01, 5.81632653e-01, 9.99694501e-01,
        1.00000000e+00],
       [7.69230769e-02, 3.44262295e-01, 5.51020408e-01, 7.52342159e-01,
        0.00000000e+00],
       [3.07692308e-01, 3.52459016e-01, 6.02040816e-01, 1.38187373e-01,
        1.00000000e+00],
       [6.15384615e-01, 3.52459016e-01, 4.59183673e-01, 6.99694501e-01,
        0.00000000e+00],
       [9.61538462e-01, 3.60655738e-01, 5.51020408e-01, 3.33197556e-01,
        1.00000000e+00],
       [0.00000000e+00, 3.60655738e-01, 4.08163265e-01, 8.74338086e-01,
        1.00000000e+00],
       [5.76923077e-01, 3.68852459e-01, 4.89795918e-01, 5.62321792e-01,
        0.00000000e+00],
       [4.23076923e-01, 3.68852459e-01, 3.97959184e-01, 3.59368635e-01,
        2.00000000e-01],
       [2.69230769e-01, 3.68852459e-01, 4.18367347e-01, 6.58350305e-01,
        6.00000000e-01],
       [1.15384615e-01, 3.68852459e-01, 5.20408163e-01, 1.26272912e-02,
        4.00000000e-01],
       [5.57692308e-01, 3.68852459e-01, 4.69387755e-01, 5.78818737e-01,
        8.00000000e-01],
       [1.73076923e-01, 3.68852459e-01, 5.00000000e-01, 4.15784114e-01,
        8.00000000e-01],
       [5.76923077e-01, 3.77049180e-01, 4.18367347e-01, 6.27800407e-01,
        6.00000000e-01],
       [3.84615385e-02, 3.77049180e-01, 4.89795918e-01, 8.58248473e-01,
        6.00000000e-01],
       [9.61538462e-02, 3.85245902e-01, 4.08163265e-01, 7.99796334e-01,
        8.00000000e-01],
       [5.96153846e-01, 3.85245902e-01, 4.79591837e-01, 8.16191446e-01,
        0.00000000e+00],
       [9.42307692e-01, 3.85245902e-01, 5.91836735e-01, 1.19857434e-01,
        0.00000000e+00],
       [1.53846154e-01, 3.85245902e-01, 5.51020408e-01, 7.41446029e-01,
        8.00000000e-01],
       [5.96153846e-01, 3.85245902e-01, 5.61224490e-01, 2.07942974e-01,
        2.00000000e-01],
       [5.76923077e-02, 3.85245902e-01, 4.18367347e-01, 1.28207739e-01,
        2.00000000e-01],
       [9.23076923e-01, 3.93442623e-01, 5.00000000e-01, 5.79938900e-01,
        8.00000000e-01],
       [6.92307692e-01, 3.93442623e-01, 4.59183673e-01, 2.43991853e-01,
        1.00000000e+00],
       [9.61538462e-01, 3.93442623e-01, 4.28571429e-01, 1.95621181e-01,
        0.00000000e+00],
       [9.23076923e-01, 3.93442623e-01, 4.79591837e-01, 9.03971487e-01,
        6.00000000e-01],
       [9.03846154e-01, 3.93442623e-01, 5.20408163e-01, 9.69450102e-01,
        0.00000000e+00],
       [1.92307692e-02, 3.93442623e-01, 5.40816327e-01, 5.69755601e-01,
        8.00000000e-01],
       [3.84615385e-01, 4.01639344e-01, 4.18367347e-01, 5.20570265e-01,
        1.00000000e+00],
       [1.92307692e-02, 4.01639344e-01, 4.59183673e-01, 6.50101833e-01,
        6.00000000e-01],
       [0.00000000e+00, 4.09836066e-01, 4.79591837e-01, 3.67006110e-01,
        6.00000000e-01],
       [1.92307692e-02, 4.09836066e-01, 5.00000000e-01, 7.02647658e-03,
        1.00000000e+00],
       [8.65384615e-01, 4.09836066e-01, 4.28571429e-01, 2.48065173e-01,
        6.00000000e-01],
       [5.96153846e-01, 4.09836066e-01, 5.91836735e-01, 6.26069246e-01,
        6.00000000e-01],
       [6.34615385e-01, 4.26229508e-01, 4.28571429e-01, 2.36863544e-01,
        6.00000000e-01],
       [6.15384615e-01, 4.26229508e-01, 5.71428571e-01, 1.12321792e-01,
        1.00000000e+00],
       [1.73076923e-01, 4.26229508e-01, 5.61224490e-01, 6.40020367e-01,
        6.00000000e-01],
       [3.84615385e-01, 4.26229508e-01, 3.97959184e-01, 3.26476578e-01,
        2.00000000e-01],
       [4.23076923e-01, 4.42622951e-01, 5.81632653e-01, 9.63238289e-01,
        1.00000000e+00],
       [4.03846154e-01, 4.42622951e-01, 9.18367347e-01, 9.94093686e-01,
        4.00000000e-01],
       [9.61538462e-02, 4.50819672e-01, 2.85714286e-01, 7.85336049e-01,
        0.00000000e+00],
       [2.50000000e-01, 4.50819672e-01, 7.75510204e-01, 3.12830957e-01,
        8.00000000e-01],
       [4.80769231e-01, 4.59016393e-01, 3.46938776e-01, 4.79226069e-01,
        4.00000000e-01],
       [4.23076923e-01, 4.59016393e-01, 9.59183673e-01, 5.49898167e-02,
        2.00000000e-01],
       [7.88461538e-01, 4.59016393e-01, 1.02040816e-01, 2.88492872e-01,
        8.00000000e-01],
       [3.84615385e-01, 4.59016393e-01, 7.55102041e-01, 2.12830957e-01,
        6.00000000e-01],
       [5.57692308e-01, 4.59016393e-01, 8.16326531e-02, 7.70468432e-01,
        0.00000000e+00],
       [4.03846154e-01, 4.59016393e-01, 7.55102041e-01, 6.49694501e-02,
        2.00000000e-01],
       [1.34615385e-01, 4.67213115e-01, 3.36734694e-01, 1.83503055e-01,
        8.00000000e-01],
       [2.50000000e-01, 4.67213115e-01, 7.14285714e-01, 1.36965377e-01,
        2.00000000e-01],
       [3.84615385e-02, 4.75409836e-01, 4.08163265e-02, 9.75560081e-02,
        8.00000000e-01],
       [2.11538462e-01, 4.75409836e-01, 8.87755102e-01, 1.27291242e-01,
        1.00000000e+00],
       [5.00000000e-01, 4.75409836e-01, 6.12244898e-02, 3.57128310e-01,
        4.00000000e-01],
       [2.69230769e-01, 4.75409836e-01, 7.34693878e-01, 7.70366599e-01,
        1.00000000e+00],
       [1.92307692e-02, 4.83606557e-01, 9.18367347e-02, 1.87576375e-01,
        0.00000000e+00],
       [3.26923077e-01, 4.83606557e-01, 7.24489796e-01, 9.16496945e-04,
        0.00000000e+00],
       [7.50000000e-01, 4.91803279e-01, 4.08163265e-02, 5.60590631e-01,
        4.00000000e-01],
       [2.69230769e-01, 4.91803279e-01, 9.38775510e-01, 7.57841141e-01,
        8.00000000e-01],
       [1.92307692e-01, 5.00000000e-01, 3.97959184e-01, 2.84725051e-01,
        6.00000000e-01],
       [2.69230769e-01, 5.00000000e-01, 8.77551020e-01, 1.79837067e-01,
        4.00000000e-01],
       [1.34615385e-01, 5.08196721e-01, 1.12244898e-01, 7.75050916e-01,
        4.00000000e-01],
       [1.92307692e-01, 5.08196721e-01, 9.79591837e-01, 7.31568228e-01,
        8.00000000e-01],
       [5.76923077e-01, 5.08196721e-01, 3.57142857e-01, 5.63136456e-01,
        6.00000000e-01],
       [2.69230769e-01, 5.08196721e-01, 7.44897959e-01, 5.48676171e-01,
        0.00000000e+00],
       [3.07692308e-01, 5.16393443e-01, 2.14285714e-01, 8.35437882e-01,
        6.00000000e-01],
       [3.07692308e-01, 5.16393443e-01, 9.08163265e-01, 2.73930754e-02,
        1.00000000e+00],
       [4.80769231e-01, 5.16393443e-01, 1.63265306e-01, 4.76985743e-01,
        1.00000000e+00],
       [4.03846154e-01, 5.16393443e-01, 8.87755102e-01, 1.78818737e-01,
        6.00000000e-01],
       [5.00000000e-01, 5.16393443e-01, 1.93877551e-01, 6.56211813e-01,
        6.00000000e-01],
       [3.84615385e-01, 5.16393443e-01, 7.65306122e-01, 8.54480652e-01,
        4.00000000e-01],
       [5.57692308e-01, 5.16393443e-01, 1.53061224e-01, 7.09979633e-01,
        8.00000000e-01],
       [1.73076923e-01, 5.16393443e-01, 8.97959184e-01, 3.47556008e-01,
        4.00000000e-01],
       [3.65384615e-01, 5.16393443e-01, 0.00000000e+00, 3.49185336e-01,
        8.00000000e-01],
       [2.30769231e-01, 5.16393443e-01, 7.85714286e-01, 5.42769857e-02,
        0.00000000e+00],
       [3.07692308e-01, 5.16393443e-01, 0.00000000e+00, 5.53258656e-01,
        4.00000000e-01],
       [2.30769231e-01, 5.16393443e-01, 7.34693878e-01, 8.28207739e-01,
        8.00000000e-01],
       [7.30769231e-01, 5.24590164e-01, 3.46938776e-01, 8.23421589e-01,
        4.00000000e-01],
       [2.11538462e-01, 5.24590164e-01, 8.36734694e-01, 7.48167006e-01,
        1.00000000e+00],
       [1.92307692e-02, 5.40983607e-01, 4.08163265e-02, 9.89205703e-01,
        2.00000000e-01],
       [2.50000000e-01, 5.40983607e-01, 9.38775510e-01, 9.45315682e-01,
        1.00000000e+00],
       [6.15384615e-01, 5.73770492e-01, 2.55102041e-01, 1.33401222e-01,
        0.00000000e+00],
       [3.46153846e-01, 5.73770492e-01, 7.55102041e-01, 4.57026477e-01,
        8.00000000e-01],
       [4.61538462e-01, 5.81967213e-01, 1.93877551e-01, 1.19042770e-01,
        0.00000000e+00],
       [2.88461538e-01, 5.81967213e-01, 9.59183673e-01, 4.87983707e-01,
        1.00000000e+00],
       [3.46153846e-01, 5.90163934e-01, 2.65306122e-01, 5.47352342e-01,
        2.00000000e-01],
       [2.69230769e-01, 5.90163934e-01, 6.32653061e-01, 8.84928717e-02,
        4.00000000e-01],
       [4.23076923e-01, 5.90163934e-01, 1.22448980e-01, 2.34114053e-01,
        1.00000000e+00],
       [1.92307692e-01, 5.90163934e-01, 7.55102041e-01, 1.23217923e-02,
        1.00000000e+00],
       [3.46153846e-01, 5.90163934e-01, 9.18367347e-02, 5.24134420e-01,
        1.00000000e+00],
       [3.46153846e-01, 5.90163934e-01, 9.28571429e-01, 3.80244399e-01,
        1.00000000e+00],
       [6.53846154e-01, 5.98360656e-01, 1.22448980e-01, 5.49389002e-01,
        6.00000000e-01],
       [2.30769231e-01, 5.98360656e-01, 8.67346939e-01, 8.01629328e-01,
        1.00000000e+00],
       [7.69230769e-01, 5.98360656e-01, 1.42857143e-01, 3.47352342e-01,
        2.00000000e-01],
       [1.73076923e-01, 5.98360656e-01, 6.93877551e-01, 2.77189409e-01,
        1.00000000e+00],
       [7.88461538e-01, 6.39344262e-01, 1.32653061e-01, 3.10590631e-01,
        0.00000000e+00],
       [3.26923077e-01, 6.39344262e-01, 9.08163265e-01, 7.63136456e-01,
        8.00000000e-01],
       [3.65384615e-01, 6.72131148e-01, 3.16326531e-01, 2.45010183e-01,
        6.00000000e-01],
       [2.69230769e-01, 6.72131148e-01, 8.67346939e-01, 1.89409369e-01,
        8.00000000e-01],
       [5.38461538e-01, 6.80327869e-01, 1.42857143e-01, 6.06924644e-02,
        1.00000000e+00],
       [2.11538462e-01, 6.80327869e-01, 8.87755102e-01, 5.31466395e-01,
        2.00000000e-01],
       [4.42307692e-01, 6.88524590e-01, 3.87755102e-01, 1.61812627e-01,
        1.00000000e+00],
       [2.30769231e-01, 6.88524590e-01, 9.79591837e-01, 3.47556008e-01,
        4.00000000e-01],
       [6.92307692e-01, 7.04918033e-01, 2.34693878e-01, 5.37474542e-01,
        6.00000000e-01],
       [1.92307692e-01, 7.04918033e-01, 6.83673469e-01, 1.82993890e-01,
        0.00000000e+00],
       [4.42307692e-01, 7.21311475e-01, 1.63265306e-01, 6.24949084e-01,
        4.00000000e-01],
       [3.46153846e-01, 7.21311475e-01, 8.57142857e-01, 7.43890020e-01,
        0.00000000e+00],
       [3.07692308e-01, 7.21311475e-01, 2.24489796e-01, 8.92973523e-01,
        8.00000000e-01],
       [2.69230769e-01, 7.21311475e-01, 6.93877551e-01, 6.91853360e-01,
        4.00000000e-01],
       [2.88461538e-01, 8.03278689e-01, 7.14285714e-02, 5.63849287e-01,
        8.00000000e-01],
       [3.84615385e-01, 8.03278689e-01, 9.18367347e-01, 3.05498982e-02,
        0.00000000e+00],
       [5.57692308e-01, 8.60655738e-01, 1.53061224e-01, 5.86558045e-01,
        2.00000000e-01],
       [3.26923077e-01, 8.60655738e-01, 7.95918367e-01, 1.14562118e-01,
        4.00000000e-01],
       [5.19230769e-01, 9.09836066e-01, 2.75510204e-01, 6.71079430e-01,
        8.00000000e-01],
       [2.69230769e-01, 9.09836066e-01, 7.44897959e-01, 1.78513238e-01,
        0.00000000e+00],
       [2.69230769e-01, 1.00000000e+00, 1.73469388e-01, 9.44704684e-01,
        4.00000000e-01],
       [2.30769231e-01, 1.00000000e+00, 8.36734694e-01, 8.18635438e-01,
        1.00000000e+00]])

In [29]:
df_mms = pd.DataFrame(df_mms,columns = scaled_df.columns)
df_mms.head()

,Age,Annual Income (k$),Spending Score (1-100),Travel_distance_meters,Dependents
0,0.019231,0.000000,NaN,0.495519,1.0
1,NaN,0.000000,0.816327,0.337882,0.6
2,0.038462,0.008197,0.051020,0.266904,0.0
3,0.096154,NaN,0.775510,0.625356,0.0
4,NaN,NaN,0.397959,0.183707,0.6

In [30]:
df_mms.describe()

,Age,Annual Income (k$),Spending Score (1-100),Travel_distance_meters,Dependents
count,197.000000,198.000000,199.000000,200.000000,200.000000
mean,0.403846,0.377091,0.502615,0.482854,0.505000
std,0.269287,0.213261,0.264044,0.284747,0.364195
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.211538,0.223361,0.341837,0.218941,0.200000
50%,0.346154,0.385246,0.500000,0.487169,0.600000
75%,0.596154,0.516393,0.734694,0.719934,0.800000
max,1.000000,1.000000,1.000000,1.000000,1.000000

In [31]:
%cd drive

/content/drive

In [32]:
%cd MyDrive/Colab_Notebooks

/content/drive/MyDrive/Colab_Notebooks

In [33]:
!git init
!git status

Reinitialized existing Git repository in /content/drive/MyDrive/Colab_Notebooks/.git/
Refresh index: 100% (10/10), done.
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   DataExploringAndPreparing.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	BC_Data.csv
	Clean_Mall_Customers_tut2.csv
	Dataset_Cleaning.ipynb
	Mall_Customers_Additional.csv
	Network_Intrusion_Dataset(1).csv

no changes added to commit (use "git add" and/or "git commit -a")

In [ ]:
!git add .
!git commit -m ""