In [5]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
data = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/loan_approval_data.csv')

In [9]:
data.head()

,id,age,income,home_ownership,emplyment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_allowed_loan
0,35437,21.0,12000,OWN,0,EDUCATION,15000,6.99,0.12,N,4,0,-2426900
1,53756,21.0,13200,OWN,2,EDUCATION,25000,16.77,0.19,Y,3,0,-111739
2,42205,23.0,9600,RENT,5,MEDICAL,30000,12.42,0.31,N,3,0,-89000
3,19180,40.0,182004,RENT,3,EDUCATION,35000,8.00,0.19,N,11,0,35000
4,28072,40.0,90000,MORTGAGE,3,HOMEIMPROVEMENT,35000,12.42,0.39,N,14,0,35000

In [11]:
list(data.columns)

['id',
 'age',
 'income',
 'home_ownership',
 'emplyment_length',
 'loan_intent',
 'loan_amount',
 'loan_interest_rate',
 'loan_income_ratio',
 'payment_default_on_file',
 'credit_history_length',
 'loan_approval_status',
 'max_allowed_loan']

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       58645 non-null  int64
 1   age                      58639 non-null  float64
 2   income                   58645 non-null  int64
 3   home_ownership           58645 non-null  object
 4   emplyment_length         58645 non-null  int64
 5   loan_intent              58645 non-null  object
 6   loan_amount              58645 non-null  int64
 7   loan_interest_rate       58634 non-null  float64
 8   loan_income_ratio        58645 non-null  float64
 9   payment_default_on_file  58640 non-null  object
 10  credit_history_length    58645 non-null  int64
 11  loan_approval_status     58645 non-null  int64
 12  max_allowed_loan         58645 non-null  int64
dtypes: float64(3), int64(7), object(3)
memory usage: 5.8+ MB

In [13]:
data.isnull().sum()

id                          0
age                         6
income                      0
home_ownership              0
emplyment_length            0
loan_intent                 0
loan_amount                 0
loan_interest_rate         11
loan_income_ratio           0
payment_default_on_file     5
credit_history_length       0
loan_approval_status        0
max_allowed_loan            0
dtype: int64

In [17]:
data[data['age'].isnull()]

,id,age,income,home_ownership,emplyment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_allowed_loan
7461,44039,NaN,30288,RENT,17,PERSONAL,5000,14.74,0.17,N,8,1,0
10456,2224,NaN,36000,RENT,5,EDUCATION,10000,10.37,0.28,N,4,0,27779
14459,2214,NaN,45432,MORTGAGE,3,PERSONAL,10000,9.88,0.22,N,7,0,37683
29241,2255,NaN,65000,MORTGAGE,5,EDUCATION,6000,7.49,0.09,N,4,0,62234
49227,44016,NaN,75000,MORTGAGE,1,EDUCATION,12500,6.03,0.16,N,10,0,111213
49298,44113,NaN,70000,RENT,3,HOMEIMPROVEMENT,4000,13.85,0.06,N,6,0,111479

In [19]:
data['age'].max()

123.0

In [21]:
data['age'].nlargest(5)

39792    123.0
54600     84.0
56540     84.0
8727      80.0
8728      80.0
Name: age, dtype: float64

In [23]:
data[data['age']==123]

,id,age,income,home_ownership,emplyment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_allowed_loan
39792,47336,123.0,36000,MORTGAGE,7,PERSONAL,6700,10.75,0.18,N,4,0,81860